[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "char"
version = "1.0.0"
authors = [{name = "Venkatesh"}]
requires-python = ">=3.7"

[tool.setuptools]
packages = ["src"]